version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microcommerce-net

  customer-db:
    image: postgres:16.3
    container_name: customer-db
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - microcommerce-net

  product-db:
    image: postgres:16.3
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - microcommerce-net

  order-db:
    image: postgres:16.3
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - microcommerce-net

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    restart: always
    depends_on:
      - customer-db
      - rabbitmq
    ports:
      - "8082:8082"
    networks:
      - microcommerce-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    restart: always
    depends_on:
      - product-db
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - microcommerce-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    restart: always
    depends_on:
      - order-db
      - rabbitmq
    ports:
      - "8083:8083"
    networks:
      - microcommerce-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - microcommerce-net
    depends_on:
      - customer-service
      - product-service
      - order-service

networks:
  microcommerce-net:
    driver: bridge
