server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://customer-service:8082
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers(?<segment>/?.*), /api/customers${segment}

        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products(?<segment>/?.*), /api/products${segment}

        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders(?<segment>/?.*), /api/orders${segment}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

